### ISSUE TITLE
ConstantFlux tracker fails 

### ISSUE THREAD

**Issue by pdoubraw** [ewquon/waketracking#3]
For a mean wake, the "ConstantFlux" tracker is failing with the following message:

> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-77-9886904425e2> in <module>
>      66                                                               flux_function=lambda u,u_tot: -u*u_tot,
>      67                                                               field_names=('u','u_tot'),
> ---> 68                                                               verbosity=10)
>      69             else:
>      70                 print('which method?')
> ~/waketracking/samwich/contour/ConstantFluxTracker.py in find_centers(self, ref_flux, flux_function, field_names, trajectory_file, outlines_file, weighted_center, contour_closure, min_contour_points, frame, Ntest, tol, check_deficit, verbosity)
>     136                                              fields=field_names,
>     137                                              vdcheck=check_deficit,
> --> 138                                              debug=(verbosity > 0))
>     139             if not info['success']:
>     140                 print('WARNING: find_contour_center was unsuccessful.')
> ~/waketracking/samwich/waketrackers.py in _find_contour_center(self, itime, target_value, weighted_center, contour_closure, min_contour_points, Ntest, tol, func, fields, vdcheck, debug)
>     867                                 Cdata.integrate_function(path, func,
>     868                                                          testfields,
> --> 869                                                          vd=vd)
>     870                         #NfnEvals += 1
>     871                         if fval is not None and (avgdeficit < 0 or vd is None):
> ~/waketracking/samwich/contour_functions.py in integrate_function(self, path, func, fields, vd, Nmin)
>     318         if vd is not None:
>     319             print(inner.shape,vd.shape)
> --> 320             vdavg = np.mean(vd.ravel()[inner])
>     321         else:
>     322             vdavg = None
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 5886 but corresponding boolean dimension is 2688
> Collapse

**Comment by ewquon** [comment]
Specifying horizontal and/or vertical wake ranges, e.g., `track(..., horz_range=(),vert_range=())`, causes problems with ConstantFluxTracker (but not ConstantAreaTracker). This is because `contour_functions._points_in_contour(path)`, which is called by `contour_functions.integrate_function()`, checks points on a truncated wake plane. However, the input velocity deficit field to `integrate_function()` appears to contain the original (not truncated) data, resuting in the index error.
